'use client'

import { ToastContainer } from "react-toastify";

import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

import ReduxProvide from "@/layouts/ReduxProvide";
import FirstCallFunction from "@/layouts/FirstCallFunction";
import HeaderFrame from "@/components/HeaderFrame";
import SearchPopupFrame from "@/components/SearchPopup";
import FooteFrame from "@/components/FooterFrame";
import { SessionProvider } from "next-auth/react";

// export const metadata: Metadata = {
// 	title: "BlogSphere",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" data-theme="dark">
			<body className={`w-full h-full overflow-y-auto`}>
				<SessionProvider>
					<ReduxProvide>
						<FirstCallFunction>
							<HeaderFrame />
							{children}
							<FooteFrame />
							<SearchPopupFrame />
						</FirstCallFunction>
					</ReduxProvide>
					<ToastContainer autoClose={2000} />
				</SessionProvider>
			</body>
		</html>
	);
}
