import type { Metadata } from "next";
import { ToastContainer, toast } from "react-toastify";

import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

import ReduxProvide from "@/layouts/ReduxProvide";
import FirstCallFunction from "@/layouts/FirstCallFunction";
import ThemeLayout from "@/layouts/ThemeLayout";

export const metadata: Metadata = {
	title: "BlogSphere",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`w-full h-[100vh] overflow-hidden flex justify-center items-center flex-col`}
			>
				<ReduxProvide>
					<ThemeLayout>
						<FirstCallFunction>{children}</FirstCallFunction>
					</ThemeLayout>
				</ReduxProvide>
				<ToastContainer autoClose={2000} />
			</body>
		</html>
	);
}
