import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Verify",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<div className={`w-full h-full absolute left-0 top-0 flex justify-center items-center bg-slate-950 p-4`}>
			{children}
		</div>
	);
}
